# 全局配置
global:
  scrape_interval:     30s #抓取间隔时间
  evaluation_interval: 30s #规则引擎执行间隔时间
  query_log_file: ./promql.log

# 告警配置
alerting:
  alertmanagers: # Alertmanagers配置
  - static_configs: # Alertmanager静态配置
    - targets: # alertmanager发送目标配置
      - localhost:9093

rule_files: # 规则文件配置
  - "rules/*.yml"

scrape_configs: # 抓取配置
  - job_name: 'prometheus' #任务 采集目标分类
    basic_auth:
      username: admin
      password: 123123
    static_configs: # 抓取目标静态配置
    - targets:
      - "localhost:9090" #抓取目标

  - job_name: "node"
    static_configs:
    - targets:
      - "localhost:9100"
      - "localhost:9101"
